---
title: "Diffusion Example"
author: "Clarissa Boyajian, Grace Lewin, Steven Cognac"
date: "5-3-2022"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
library(tidyverse)
library(deSolve)
library(here)
source(here("R/diffusion.R"))

```


```{r, include=FALSE}

# run our diffusion model (iterative difference equation) with initial concentration of 10, for 8 timestep (size 1m), and 10 space steps (size 1s)
# using diffusion parameters 0.5 s/m2, 10 m2
result = diff1(initialC=10, nx=10, dx=1, nt=8, dt=1, D=0.5, area=10)

# a list is returned with our 3 data frames for concentration (conc), qin and qout
result

# used filled contour to plot results
head(result$conc)
filled.contour(result$conc, xlab="Time", ylab="Distance")

# or if you prefer this orientation (Distance on x axis)
filled.contour(t(result$conc), ylab="Time", xlab="Distance")
```


```{r include=FALSE}
# changes diffusivity and other parameters particularly
# diffusivity, dx and dt
res=diff1(initialC=10,nx=10,dx=1,nt=10,dt=30,D=0.006,area=1)

filled.contour(res$conc, xlab="Time", ylab="Distance")


# we can also see how much material moved from place to place each time step
filled.contour(res$qin, xlab="Time", ylab="Distance")

```
# play with time step, space step and parameters

```{r eval=TRUE}
# changes diffusivity and other parameters particularly
# diffusivity, dx and dt

# Looking at initial concentration of 100 mg/L and 20 meters in 1 meter intervals. Looking at a total of 10 minutes in 30 sec intervals. Diffusivity of 0.03 s/m2
res = diff1(initialC = 100,
            nx=20,
            dx=1,
            nt=20,
            dt=30,
            D=0.03,
            area=1)
filled.contour(res$conc, xlab="Time", ylab="Distance")

# Looking at initial concentration of 100 mg/L and 20 meters in 1 meter intervals. Looking at a total of 2.5 minutes in 30 sec intervals. Diffusivity of 0.003 s/m2. Moving 10x faster. Takes less time to diffuse a square meter
res = diff1(initialC = 100,
            nx=20,
            dx=1,
            nt=20,
            dt=30,
            D=0.003,
            area=1)
filled.contour(res$conc, xlab="Time", ylab="Distance")
```

