---
title: "sensitivity_ode"
author: "Steven Cognac"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(deSolve)
library(sensitivity)
library(here)
library(tidyverse)

source(here("R/dexppop_play.R"))
dexppop_play
```

## Run Sobel Analysis

Initial setup for Sobel indices

```{r}
# come up with first set of sample parameters
# we will assume that we know the initial population,

Pinitial=10

# want to learn about sensitivity to growth rate (r) and carrying capacity 
# set the number of parameters
np=100
carry_capacity = rnorm(mean=400, sd=50, n=np)
r = rnorm(mean=0.01, sd=0.005, n=np)
X1 = cbind.data.frame(r=r, carry_capacity=carry_capacity)

# repeat to get our second set of samples
carry_capacity = rnorm(mean=400, sd=50, n=np)
r = rnorm(mean=0.02, sd=0.005, n=np)
X2 = cbind.data.frame(r=r, carry_capacity=carry_capacity)

# create our sobel object and get sets ofparameters for running the model

sens_P = sobolSalt(model = NULL,X1, X2, nboot = 300)

# our parameter sets are
head(sens_P$X)
```

Rename column names

```{r}
# lets add names 
colnames(sens_P$X) = c("r","carry_capacity")

sens_P$X[1,]
```

rRun Sobel analysis

```{r}
# gets results for 200 years (evaluating every year)
simtimes = seq(from=1, to=200)
parms = list(r=sens_P$X[1,"r"], carry_capacity=sens_P$X[1,"carry_capacity"])

# or
parms = list(r=as.data.frame(sens_P$X)$r[1], carry_capacity=as.data.frame(sens_P$X)$carry_capacity[1])

result = ode(y=Pinitial, times=simtimes, func=dexppop_play, parms=parms)


colnames(result)=c("time","P")
# turn it into a data frame
result = as.data.frame(result)


head(result)
```

## Create function to compute metrics

```{r metrics}
# turn computing our metrics into a function

compute_metrics = function(result) {
  maxpop = max(result$P)
idx = which.max(result$P)
maxyear = result$time[idx]
return(list(maxpop=maxpop, maxyear=maxyear))}

# try it on our first parameter set
compute_metrics(result)

```

## Create wrapper function that combines Sobel analysis & metric functions

```{r wrapper_function}
# great but we need to apply the ode and this function for all of our parameters

# define a wrapper function to do everything we need - run solver and compute metrics - and send back results for each parameter

p_wrapper = function(r,carry_capacity, Pinitial, simtimes, func) {
    parms = list(r=r, carry_capacity=carry_capacity)
    result = ode(y=Pinitial, times=simtimes, func=func, parms=parms) 
    colnames(result)=c("time","P")
  # get metrics
  metrics=compute_metrics(as.data.frame(result))
  return(metrics)
}

```

## Map outputs

```{r map_function}
# now use pmap as we did before

allresults = as.data.frame(sens_P$X) %>% pmap(p_wrapper, Pinitial=Pinitial, simtimes=simtimes, func=dexppop_play)
```
